### ISSUE TITLE
ImportError: Cannot Import Session

### ISSUE THREAD

**Issue by saadmanrafat** [kennethreitz/twitter-scraper#15]
from twitter_scraper import get_tweets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\twitter\env\lib\site-packages\twitter_scraper.py", line 2, in <module>
    from requests_html import Session, HTML
ImportError: cannot import name 'Session'

I manually installed requests-html through pip

**Comment by Red5d** [comment]
"Session" was renamed to "HTMLSession" in requests_html. I just created a PR for this: #16
