### ISSUE TITLE
IndexError thrown when trying to parse tagged users

### ISSUE THREAD

**Issue by Recursing** [kennethreitz/twitter-scraper#32]
```
from twitter_scraper import get_tweets
next(get_tweets("socgaudenti"))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.6/site-packages/twitter_scraper.py", line 78, in get_tweets
    yield from gen_tweets(pages)
  File ".../python3.6/site-packages/twitter_scraper.py", line 35, in gen_tweets
    text = tweet.find('.tweet-text')[0].full_text
IndexError: list index out of range
```

It seems to be triggered by the "Tagged users" at the bottom of https://twitter.com/socgaudenti/status/975725303808086016 (I'm new to twitter)

A simple fix could be discarding those elements

**Comment by Civmwa** [comment]
@Recursing I'm also getting the same error. Were you able to fix it?
![twitter_scraper error](https://user-images.githubusercontent.com/38909818/45732028-25be5100-bbe3-11e8-9869-022df0d61412.PNG)

**Comment by Civmwa** [comment]
@Recursing please elaborate when you say "A simple fix could be discarding those elements". Thanks!

**Comment by Civmwa** [comment]
Putting a try and except IndexError makes it readable

**Comment by ParthS007** [comment]
Closing due to inactivity :+1:
