### ISSUE TITLE
Tweets with videos error out looking for index(".jpg")

### ISSUE THREAD

**Issue by BenQuigley** [kennethreitz/twitter-scraper#35]
Example usage:

```
for t in get_tweets(twitter, pages=n):
    ...
```

Error:

```
Getting 4 tweets from ggreenwald
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    main()
  File "bot.py", line 24, in main
    tweets = combine_tweets()
  File "bot.py", line 14, in combine_tweets
    for t in get_tweets(twitter, pages=n):
  File "/home/ben/local/bot/env/lib/python3.6/site-packages/twitter_scraper.py", line 78, in get_tweets
    yield from gen_tweets(pages)
  File "/home/ben/local/bot/env/lib/python3.6/site-packages/twitter_scraper.py", line 57, in gen_tweets
    video_id = tmp[:tmp.index('.jpg')]
ValueError: substring not found
```

**Comment by BenQuigley** [comment]
Pull request to fix: https://github.com/kennethreitz/twitter-scraper/pull/36
