### ISSUE TITLE
IndexError: list index out of range while tweet start with an emoji

### ISSUE THREAD

**Issue by jorginaarres** [kennethreitz/twitter-scraper#50]
### Example usage :

from twitter_scraper import get_tweets

for tweet in get_tweets('la_UPC', pages=1):
    print(tweet['text'])

### Error:

Traceback (most recent call last):
 File ".../main.py", line 156, in <module>
   for tweet in get_tweets('la_UPC', pages=1):
 File ".../twitter_scraper.py", line 78, in get_tweets
   yield from gen_tweets(pages)
 File ".../twitter_scraper.py", line 35, in gen_tweets
   text = tweet.find('.tweet-text')[0].full_text
IndexError: list index out of range

**Comment by ozcanyarimdunya** [comment]
Issue solved. Check #52 .
