### ISSUE TITLE
How to get the text of only the first tweet (most recent one)

### ISSUE THREAD

**Issue by nikitavoloboev** [kennethreitz/twitter-scraper#7]
For example from [my Twitter profile](https://twitter.com/nikitavoloboev), I want to only get `Wrote about my workflow in making workflows` back. As well as the link attached to the tweet.

It would be even more awesome if you could also get back the link to the media (image/video) that is attached (embedded) to the tweet. 

I really hope it is possible to do. Thank you for sharing this.

**Comment by aldnav** [comment]
I kind of saw similar tweet format too where links aren't in the tweet text because it belonged on a different element on the markup. Will try to hash out something later.

For getting only the first tweet you can do,

```py
print('Getting tweets for %s' % user)
print(list(get_tweets(user, pages=1))[0])  # convert gen to list first then access subscripts

# twitter_scraper.py
yield re.sub('http', ' http', tweet, 1)  # quick fix on concatenated link 
```
```sh
Getting tweets for nikitavoloboev
Wrote about my workflow in making workflows https://www.alfredforum.com/topic/11274-my-workflow-in-making-workflows …
```

**Comment by nikitavoloboev** [comment]
Thank you @aldnav

**Comment by nikitavoloboev** [comment]
Hey @aldnav 

I tried running your example with this code:

```Python
from twitter_scraper import get_tweets

user = "nikitavoloboev"
print(list(get_tweets(user, pages=1))[0])
```

But when ran, I get this error:

```Bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyquery/pyquery.py", line 95, in fromstring
    result = getattr(etree, meth)(context)
  File "src/lxml/etree.pyx", line 3230, in lxml.etree.fromstring (src/lxml/etree.c:81070)
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument (src/lxml/etree.c:121250)
  File "src/lxml/parser.pxi", line 1752, in lxml.etree._parseDoc (src/lxml/etree.c:119804)
  File "src/lxml/parser.pxi", line 1066, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/etree.c:113546)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "<string>", line 2
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 2, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    print(list(get_tweets(user, pages=1))[0])
  File "/usr/local/lib/python3.7/site-packages/twitter_scraper.py", line 30, in get_tweets
    yield from gen_tweets(pages)
  File "/usr/local/lib/python3.7/site-packages/twitter_scraper.py", line 18, in gen_tweets
    d = pq(r.json()['items_html'])
  File "/usr/local/lib/python3.7/site-packages/pyquery/pyquery.py", line 255, in __init__
    elements = fromstring(context, self.parser)
  File "/usr/local/lib/python3.7/site-packages/pyquery/pyquery.py", line 99, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "/usr/local/lib/python3.7/site-packages/lxml/html/__init__.py", line 876, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/lib/python3.7/site-packages/lxml/html/__init__.py", line 765, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty
```

**Comment by nikitavoloboev** [comment]
> Have you pulled from the latest master?

Not sure what you mean. I ran `pip install twitter_scraper` then pt the code above and tried to ran it.

`pipenv` is [broken for me](https://github.com/pypa/pipenv/issues/1480) for some reason.

**Comment by aldnav** [comment]
I see. I don't think the latest fixes are in the release yet. I'm not sure what's the best course of action here. If you may, you can opt to pull this repository to keep updated.
